package com.rajibuilt.codeBook;

import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import java.util.ArrayList;
import java.util.List;

@RestController
public class CountryController {

    @RequestMapping(value = "country", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseBody
    public List<Country> countryList() {


        Country And = new Country("AD", "Andorra");
        Country Uni = new Country("AE", "United Arab Emirates");
        Country Afg = new Country("AF", "Afghanistan");
        Country Ant = new Country("AG", "Antigua And Barbuda");
        Country Ang = new Country("AI", "Anguilla");
        Country Alb = new Country("AL", "Albania");
        Country Arm = new Country("AM", "Armenia");
        Country Net = new Country("AN", "Netherlands Antilles");
        Country Angl = new Country("AO", "Angola");
        Country Anta = new Country("AQ", "Antarctica");
        Country Arg = new Country("AR", "Argentina");
        Country Ame = new Country("AS", "American Samoa");
        Country Aus = new Country("AT", "Austria");
        Country Aust = new Country("AU", "Australia");
        Country Aru = new Country("AW", "Aruba");
        Country Aze = new Country("AZ", "Azerbaijan");
        Country Bos = new Country("BA", "Bosnia And Herzegovina");
        Country Bar = new Country("BB", "Barbados");
        Country Ban = new Country("BD", "Bangladesh");
        Country Bel = new Country("BE", "Belgium");
        Country Bur = new Country("BF", "Burkina Faso");
        Country Bul = new Country("BG", "Bulgaria");
        Country Bah = new Country("BH", "Bahrain");
        Country Burn = new Country("BI", "Burundi");
        Country Ben = new Country("BJ", "Benin");
        Country Ber = new Country("BM", "Bermuda");
        Country Bru = new Country("BN", "Brunei Darussalam");
        Country Bol = new Country("BO", "Bolivia");
        Country Bra = new Country("BR", "Brazil");
        Country Baha = new Country("BS", "Bahamas");
        Country Bhu = new Country("BT", "Bhutan");
        Country Bou = new Country("BV", "Bouvet Island");
        Country Bot = new Country("BW", "Botswana");
        Country Bela = new Country("BY", "Belarus");
        Country Beli = new Country("BZ", "Belize");
        Country Can = new Country("CA", "Canada");
        Country Coc = new Country("CC", "Cocos (keeling) Islands");
        Country Con = new Country("CD", "Congo, The Democratic Republic Of The");
        Country Cen = new Country("CF", "Central African Republic");
        Country Cong = new Country("CG", "Congo");
        Country Swi = new Country("CH", "Switzerland");
        Country Cot = new Country("CI", "Cote Divoire");
        Country Coo = new Country("CK", "Cook Islands");
        Country Chi = new Country("CL", "Chile");
        Country Cam = new Country("CM", "Cameroon");
        Country Chin = new Country("CN", "China");
        Country Col = new Country("CO", "Colombia");
        Country Cos = new Country("CR", "Costa Rica");
        Country Cub = new Country("CU", "Cuba");
        Country Cap = new Country("CV", "Cape Verde");
        Country Chr = new Country("CX", "Christmas Island");
        Country Cyp = new Country("CY", "Cyprus");
        Country Cze = new Country("CZ", "Czech Republic");
        Country Ger = new Country("DE", "Germany");
        Country Dji = new Country("DJ", "Djibouti");
        Country Den = new Country("DK", "Denmark");
        Country Dom = new Country("DM", "Dominica");
        Country Domi = new Country("DO", "Dominican Republic");
        Country Alg = new Country("DZ", "Algeria");
        Country Ecu = new Country("EC", "Ecuador");
        Country Est = new Country("EE", "Estonia");
        Country Egy = new Country("EG", "Egypt");
        Country Wes = new Country("EH", "Western Sahara");
        Country Eri = new Country("ER", "Eritrea");
        Country Spa = new Country("ES", "Spain");
        Country Eth = new Country("ET", "Ethiopia");
        Country Fin = new Country("FI", "Finland");
        Country Fij = new Country("FJ", "Fiji");
        Country Fal = new Country("FK", "Falkland Islands (malvinas)");
        Country Mic = new Country("FM", "Micronesia, Federated States Of");
        Country Far = new Country("FO", "Faroe Islands");
        Country Fra = new Country("FR", "France");
        Country Gab = new Country("GA", "Gabon");
        Country Uk = new Country("GB", "United Kingdom");
        Country Gre = new Country("GD", "Grenada");
        Country Geo = new Country("GE", "Georgia");
        Country Fre = new Country("GF", "French Guiana");
        Country Gha = new Country("GH", "Ghana");
        Country Gib = new Country("GI", "Gibraltar");
        Country Gren = new Country("GL", "Greenland");
        Country Gam = new Country("GM", "Gambia");
        Country Gui = new Country("GN", "Guinea");
        Country Gua = new Country("GP", "Guadeloupe");
        Country Equ = new Country("GQ", "Equatorial Guinea");
        Country Grec = new Country("GR", "Greece");
        Country Sou = new Country("GS", "South Georgia And The South Sandwich Islands");
        Country Guat = new Country("GT", "Guatemala");
        Country Guam = new Country("GU", "Guam");
        Country Guin = new Country("GW", "Guinea-bissau");
        Country Guy = new Country("GY", "Guyana");
        Country Hon = new Country("HK", "Hong Kong");
        Country Hea = new Country("HM", "Heard Island And Mcdonald Islands");
        Country Hond = new Country("HN", "Honduras");
        Country Cro = new Country("HR", "Croatia");
        Country Hai = new Country("HT", "Haiti");
        Country Hun = new Country("HU", "Hungary");
        Country Ind = new Country("ID", "Indonesia");
        Country Ire = new Country("IE", "Ireland");
        Country Isr = new Country("IL", "Israel");
        Country Indi = new Country("IN", "India");
        Country Bri = new Country("IO", "British Indian Ocean Territory");
        Country Ira = new Country("IQ", "Iraq");
        Country Iran = new Country("IR", "Iran, Islamic Republic Of");
        Country Ice = new Country("IS", "Iceland");
        Country Ita = new Country("IT", "Italy");
        Country Jam = new Country("JM", "Jamaica");
        Country Jor = new Country("JO", "Jordan");
        Country Jap = new Country("JP", "Japan");
        Country Ken = new Country("KE", "Kenya");
        Country Kyr = new Country("KG", "Kyrgyzstan");
        Country Camb = new Country("KH", "Cambodia");
        Country Kir = new Country("KI", "Kiribati");
        Country Com = new Country("KM", "Comoros");
        Country Sai = new Country("KN", "Saint Kitts And Nevis");
        Country Kor = new Country("KP", "Korea, Democratic Peoples Republic Of");
        Country Kore = new Country("KR", "Korea, Republic Of");
        Country Kos = new Country("KV", "Kosovo");
        Country Kuw = new Country("KW", "Kuwait");
        Country Cay = new Country("KY", "Cayman Islands");
        Country Kaz = new Country("KZ", "Kazakstan");
        Country Lao = new Country("LA", "Lao Peoples Democratic Republic");
        Country Leb = new Country("LB", "Lebanon");
        Country Sain = new Country("LC", "Saint Lucia");
        Country Lie = new Country("LI", "Liechtenstein");
        Country Sri = new Country("LK", "Sri Lanka");
        Country Lib = new Country("LR", "Liberia");
        Country Les = new Country("LS", "Lesotho");
        Country Lit = new Country("LT", "Lithuania");
        Country Lux = new Country("LU", "Luxembourg");
        Country Lat = new Country("LV", "Latvia");
        Country Liby = new Country("LY", "Libyan Arab Jamahiriya");
        Country Mor = new Country("MA", "Morocco");
        Country Mon = new Country("MC", "Monaco");
        Country Mol = new Country("MD", "Moldova, Republic Of");
        Country Mont = new Country("ME", "Montenegro");
        Country Mad = new Country("MG", "Madagascar");
        Country Mar = new Country("MH", "Marshall Islands");
        Country Mac = new Country("MK", "Macedonia, The Former Yugoslav Republic Of");
        Country Mal = new Country("ML", "Mali");
        Country Mya = new Country("MM", "Myanmar");
        Country Mong = new Country("MN", "Mongolia");
        Country Macc = new Country("MO", "Macau");
        Country Nor = new Country("MP", "Northern Mariana Islands");
        Country Mart = new Country("MQ", "Martinique");
        Country Mau = new Country("MR", "Mauritania");
        Country Mons = new Country("MS", "Montserrat");
        Country Mat = new Country("MT", "Malta");
        Country Mr = new Country("MU", "Mauritius");
        Country Madl = new Country("MV", "Maldives");
        Country Ml = new Country("MW", "Malawi");
        Country Mex = new Country("MX", "Mexico");
        Country Maly = new Country("MY", "Malaysia");
        Country Moz = new Country("MZ", "Mozambique");
        Country Nam = new Country("NA", "Namibia");
        Country New = new Country("NC", "New Caledonia");
        Country Nig = new Country("NE", "Niger");
        Country Nort = new Country("NF", "Norfolk Island");
        Country Ngr = new Country("NG", "Nigeria");
        Country Nic = new Country("NI", "Nicaragua");
        Country Ntd = new Country("NL", "Netherlands");
        Country Nwy = new Country("NO", "Norway");
        Country Nep = new Country("NP", "Nepal");
        Country Nau = new Country("NR", "Nauru");
        Country Niu = new Country("NU", "Niue");
        Country Nz = new Country("NZ", "New Zealand");
        Country Oma = new Country("OM", "Oman");
        Country Pan = new Country("PA", "Panama");
        Country Per = new Country("PE", "Peru");
        Country Frp = new Country("PF", "French Polynesia");
        Country Pap = new Country("PG", "Papua New Guinea");
        Country Phi = new Country("PH", "Philippines");
        Country Pak = new Country("PK", "Pakistan");
        Country Pol = new Country("PL", "Poland");
        Country SPM = new Country("PM", "Saint Pierre And Miquelon");
        Country Pit = new Country("PN", "Pitcairn");
        Country Pue = new Country("PR", "Puerto Rico");
        Country Pal = new Country("PS", "Palestinian Territory, Occupied");
        Country Por = new Country("PT", "Portugal");
        Country Palau = new Country("PW", "Palau");
        Country Par = new Country("PY", "Paraguay");
        Country Qat = new Country("QA", "Qatar");
        Country Reu = new Country("RE", "Reunion");
        Country Rom = new Country("RO", "Romania");
        Country Ser = new Country("RS", "Serbia");
        Country Rus = new Country("RU", "Russian Federation");
        Country Rwa = new Country("RW", "Rwanda");
        Country Sau = new Country("SA", "Saudi Arabia");
        Country Sol = new Country("SB", "Solomon Islands");
        Country Sey = new Country("SC", "Seychelles");
        Country Sud = new Country("SD", "Sudan");
        Country Swe = new Country("SE", "Sweden");
        Country Sin = new Country("SG", "Singapore");
        Country SH = new Country("SH", "Saint Helena");
        Country Slo = new Country("SI", "Slovenia");
        Country Sva = new Country("SJ", "Svalbard And Jan Mayen");
        Country SlK = new Country("SK", "Slovakia");
        Country Sie = new Country("SL", "Sierra Leone");
        Country San = new Country("SM", "San Marino");
        Country Sen = new Country("SN", "Senegal");
        Country Som = new Country("SO", "Somalia");
        Country Sur = new Country("SR", "Suriname");
        Country Sao = new Country("ST", "Sao Tome And Principe");
        Country El = new Country("SV", "El Salvador");
        Country Syr = new Country("SY", "Syrian Arab Republic");
        Country Swa = new Country("SZ", "Swaziland");
        Country Tur = new Country("TC", "Turks And Caicos Islands");
        Country Cha = new Country("TD", "Chad");
        Country Frc = new Country("TF", "French Southern Territories");
        Country Tog = new Country("TG", "Togo");
        Country Tha = new Country("TH", "Thailand");
        Country Taj = new Country("TJ", "Tajikistan");
        Country Tok = new Country("TK", "Tokelau");
        Country Trk = new Country("TM", "Turkmenistan");
        Country Tun = new Country("TN", "Tunisia");
        Country Ton = new Country("TO", "Tonga");
        Country Eas = new Country("TP", "East Timor");
        Country Tk = new Country("TR", "Turkey");
        Country Tri = new Country("TT", "Trinidad And Tobago");
        Country Tuv = new Country("TV", "Tuvalu");
        Country Tai = new Country("TW", "Taiwan, Province Of China");
        Country Tan = new Country("TZ", "Tanzania, United Republic Of");
        Country Ukr = new Country("UA", "Ukraine");
        Country Uga = new Country("UG", "Uganda");
        Country UMS = new Country("UM", "United States Minor Outlying Islands");
        Country US = new Country("US", "United States");
        Country Uru = new Country("UY", "Uruguay");
        Country Uzb = new Country("UZ", "Uzbekistan");
        Country Hol = new Country("VA", "Holy See (vatican City State)");
        Country SCS = new Country("VC", "Saint Vincent And The Grenadines");
        Country Ven = new Country("VE", "Venezuela");
        Country Vir = new Country("VG", "Virgin Islands, British");
        Country Vis = new Country("VI", "Virgin Islands, U.s.");
        Country Vie = new Country("VN", "Viet Nam");
        Country Van = new Country("VU", "Vanuatu");
        Country Wal = new Country("WF", "Wallis And Futuna");
        Country Sam = new Country("WS", "Samoa");
        Country Yem = new Country("YE", "Yemen");
        Country May = new Country("YT", "Mayotte");
        Country SA = new Country("ZA", "South Africa");
        Country Zam = new Country("ZM", "Zambia");
        Country Zim = new Country("ZW", "Zimbabwe");


        List<Country> list = new ArrayList<>();
        list.add(And);
        list.add(Uni);
        list.add(Afg);
        list.add(Ant);
        list.add(Ang);
        list.add(Alb);
        list.add(Arm);
        list.add(Net);
        list.add(Angl);
        list.add(Anta);
        list.add(Arg);
        list.add(Ame);
        list.add(Aus);
        list.add(Aust);
        list.add(Aru);
        list.add(Aze);
        list.add(Bos);
        list.add(Bar);
        list.add(Ban);
        list.add(Bel);
        list.add(Bur);
        list.add(Bul);
        list.add(Bah);
        list.add(Burn);
        list.add(Ben);
        list.add(Ber);
        list.add(Bru);
        list.add(Bol);
        list.add(Bra);
        list.add(Baha);
        list.add(Bhu);
        list.add(Bou);
        list.add(Bot);
        list.add(Bela);
        list.add(Beli);
        list.add(Can);
        list.add(Coc);
        list.add(Con);
        list.add(Cen);
        list.add(Cong);
        list.add(Swi);
        list.add(Cot);
        list.add(Coo);
        list.add(Chi);
        list.add(Cam);
        list.add(Chin);
        list.add(Col);
        list.add(Cos);
        list.add(Cub);
        list.add(Cap);
        list.add(Chr);
        list.add(Cyp);
        list.add(Cze);
        list.add(Ger);
        list.add(Dji);
        list.add(Den);
        list.add(Dom);
        list.add(Domi);
        list.add(Alg);
        list.add(Ecu);
        list.add(Est);
        list.add(Egy);
        list.add(Wes);
        list.add(Eri);
        list.add(Spa);
        list.add(Eth);
        list.add(Fin);
        list.add(Fij);
        list.add(Fal);
        list.add(Mic);
        list.add(Far);
        list.add(Fra);
        list.add(Gab);
        list.add(Uk);
        list.add(Gre);
        list.add(Geo);
        list.add(Fre);
        list.add(Gha);
        list.add(Gib);
        list.add(Gren);
        list.add(Gam);
        list.add(Gui);
        list.add(Gua);
        list.add(Equ);
        list.add(Grec);
        list.add(Sou);
        list.add(Guat);
        list.add(Guam);
        list.add(Guin);
        list.add(Guy);
        list.add(Hon);
        list.add(Hea);
        list.add(Hond);
        list.add(Cro);
        list.add(Hai);
        list.add(Hun);
        list.add(Ind);
        list.add(Ire);
        list.add(Isr);
        list.add(Indi);
        list.add(Bri);
        list.add(Ira);
        list.add(Iran);
        list.add(Ice);
        list.add(Ita);
        list.add(Jam);
        list.add(Jor);
        list.add(Jap);
        list.add(Ken);
        list.add(Kyr);
        list.add(Camb);
        list.add(Kir);
        list.add(Com);
        list.add(Sai);
        list.add(Kor);
        list.add(Kore);
        list.add(Kos);
        list.add(Kuw);
        list.add(Cay);
        list.add(Kaz);
        list.add(Lao);
        list.add(Leb);
        list.add(Sain);
        list.add(Lie);
        list.add(Sri);
        list.add(Lib);
        list.add(Les);
        list.add(Lit);
        list.add(Lux);
        list.add(Lat);
        list.add(Liby);
        list.add(Mor);
        list.add(Mon);
        list.add(Mol);
        list.add(Mont);
        list.add(Mad);
        list.add(Mar);
        list.add(Mac);
        list.add(Mal);
        list.add(Mya);
        list.add(Mong);
        list.add(Macc);
        list.add(Nor);
        list.add(Mart);
        list.add(Mau);
        list.add(Mons);
        list.add(Mat);
        list.add(Mr);
        list.add(Madl);
        list.add(Ml);
        list.add(Mex);
        list.add(Maly);
        list.add(Moz);
        list.add(Nam);
        list.add(New);
        list.add(Nig);
        list.add(Nort);
        list.add(Ngr);
        list.add(Nic);
        list.add(Ntd);
        list.add(Nwy);
        list.add(Nep);
        list.add(Nau);
        list.add(Niu);
        list.add(Nz);
        list.add(Oma);
        list.add(Pan);
        list.add(Per);
        list.add(Frp);
        list.add(Pap);
        list.add(Phi);
        list.add(Pak);
        list.add(Pol);
        list.add(SPM);
        list.add(Pit);
        list.add(Pue);
        list.add(Pal);
        list.add(Por);
        list.add(Palau);
        list.add(Par);
        list.add(Qat);
        list.add(Reu);
        list.add(Rom);
        list.add(Ser);
        list.add(Rus);
        list.add(Rwa);
        list.add(Sau);
        list.add(Sol);
        list.add(Sey);
        list.add(Sud);
        list.add(Swe);
        list.add(Sin);
        list.add(SH);
        list.add(Slo);
        list.add(Sva);
        list.add(SlK);
        list.add(Sie);
        list.add(San);
        list.add(Sen);
        list.add(Som);
        list.add(Sur);
        list.add(Sao);
        list.add(El);
        list.add(Syr);
        list.add(Swa);
        list.add(Tur);
        list.add(Cha);
        list.add(Frc);
        list.add(Tog);
        list.add(Tha);
        list.add(Taj);
        list.add(Tok);
        list.add(Trk);
        list.add(Tun);
        list.add(Ton);
        list.add(Eas);
        list.add(Tk);
        list.add(Tri);
        list.add(Tuv);
        list.add(Tai);
        list.add(Tan);
        list.add(Ukr);
        list.add(Uga);
        list.add(UMS);
        list.add(US);
        list.add(Uru);
        list.add(Uzb);
        list.add(Hol);
        list.add(SCS);
        list.add(Ven);
        list.add(Vir);
        list.add(Vis);
        list.add(Vie);
        list.add(Van);
        list.add(Wal);
        list.add(Sam);
        list.add(Yem);
        list.add(May);
        list.add(SA);
        list.add(Zam);
        list.add(Zim);

        return list;

    }


    public class Country {
        private String countryCode;
        private String countryName;


        public Country(String countryCode, String countryName) {
            this.countryCode = countryCode;
            this.countryName = countryName;
        }

        public String getCountryCode() {
            return countryCode;
        }

        public void setCountryCode(String countryCode) {
            this.countryCode = countryCode;
        }

        public String getCountryName() {
            return countryName;
        }

        public void setCountryName(String countryName) {
            this.countryName = countryName;
        }
    }
}