package com.rajibuilt.codeBook;


import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import java.util.ArrayList;
import java.util.List;

    @RestController
    public class LgaController {

        @RequestMapping(value = "lga", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
        @ResponseBody
        public List<Lga> lgaList() {

            Lga Aba_North               = new Lga("AB001", "Aba North");
            Lga Aba_South               = new Lga("AB002", "Aba South");
            Lga Arochukwu               = new Lga("AB003", "Arochukwu");
            Lga Bende                   = new Lga("AB004", "Bende");
            Lga Ikwauano                = new Lga("AB005", "Ikwauano");
            Lga Isiala_Ngwa_North       = new Lga("AB006", "Isiala-Ngwa North");
            Lga Isiala_Ngwa_South       = new Lga("AB007", "Isiala-Ngwa South");
            Lga Isuikwuato              = new Lga("AB008", "Isuikwuato");
            Lga Obi_Ngwa                = new Lga("AB009", "Obi Ngwa");
            Lga Ohafia                  = new Lga("AB010", "Ohafia");
            Lga Osisioma_Ngwa           = new Lga("AB011", "Osisioma Ngwa");
            Lga Ugwunagbo               = new Lga("AB012", "Ugwunagbo");
            Lga Ukwa_East               = new Lga("AB013", "Ukwa East");
            Lga Ukwa_West               = new Lga("AB014", "Ukwa West");
            Lga Umuahia_North           = new Lga("AB015", "Umuahia North");
            Lga Umuahia_South           = new Lga("AB016", "Umuahia South");
            Lga Umu_Nneochi             = new Lga("AB017", "Umu-Nneochi");
            Lga Demsa                   = new Lga("AD001", "Demsa");
            Lga Fufore                  = new Lga("AD002", "Fufore");
            Lga Ganye                   = new Lga("AD003", "Ganye");
            Lga Girie                   = new Lga("AD004", "Girie");
            Lga Gombi                   = new Lga("AD005", "Gombi");
            Lga Guyuk                   = new Lga("AD006", "Guyuk");
            Lga Hong                    = new Lga("AD007", "Hong");
            Lga Jada                    = new Lga("AD008", "Jada");
            Lga Larmurde                = new Lga("AD009", "Larmurde");
            Lga Madagali                = new Lga("AD010", "Madagali");
            Lga Maiha                   = new Lga("AD011", "Maiha");
            Lga Mayo_Belwa              = new Lga("AD012", "Mayo-Belwa");
            Lga Michika                 = new Lga("AD013", "Michika");
            Lga Mubi_North              = new Lga("AD014", "Mubi North");
            Lga Mubi_South              = new Lga("AD015", "Mubi South");
            Lga Numan                   = new Lga("AD016", "Numan");
            Lga Shelleng                = new Lga("AD017", "Shelleng");
            Lga Song                    = new Lga("AD018", "Song");
            Lga Teungo                  = new Lga("AD019", "Teungo");
            Lga Yola_North              = new Lga("AD020", "Yola North");
            Lga Yola_South              = new Lga("AD021", "Yola South");
            Lga Eket                    = new Lga("AI001", "Eket");
            Lga Onna                    = new Lga("AI002", "Onna");
            Lga Nsit_Ubium              = new Lga("AI003", "Nsit Ubium");
            Lga Etinan                  = new Lga("AI004", "Etinan");
            Lga Mkpat_Enin              = new Lga("AI005", "Mkpat Enin");
            Lga Uyo                     = new Lga("AI006", "Uyo");
            Lga Ibiono_Ibom             = new Lga("AI007", "Ibiono Ibom");
            Lga Itu                     = new Lga("AI008", "Itu");
            Lga Urue_Offong_Oruko        = new Lga("AI0091", "Urue Offong/Orukoh");
            Lga Okobo                   = new Lga("AI010", "Okobo");
            Lga Oron                    = new Lga("AI011", "Oron");
            Lga Etim_Ekpo               = new Lga("AI012", "Etim Ekpo");
            Lga Ika                     = new Lga("AI013", "Ika");
            Lga Abak                    = new Lga("AI014", "Abak");
            Lga Ini                     = new Lga("AI015", "Ini");
            Lga Essien_Udim             = new Lga("AI016", "Essien Udim");
            Lga Ikono                   = new Lga("AI017", "Ikono");
            Lga Ikot_Ekpene             = new Lga("AI018", "Ikot Ekpene");
            Lga Obot_Akare              = new Lga("AI019", "Obot Akare");
            Lga Uka_Nafun               = new Lga("AI020", "Uka Nafun");
            Lga Esit_Eket               = new Lga("AI021", "Esit Eket");
            Lga Mbo                     = new Lga("AI022", "Mbo");
            Lga Eastern_Obolo           = new Lga("AI023", "Eastern Obolo");
            Lga Ibeno                   = new Lga("AI024", "Ibeno ");
            Lga Ikot_Abasi              = new Lga("AI025", "Ikot Abasi");
            Lga Udung_Uko               = new Lga("AI026", "Udung Uko");
            Lga Oruk_Anam               = new Lga("AI027", "Oruk Anam");
            Lga Ibesikpo_Asutan         = new Lga("AI028", "Ibesikpo Asutan");
            Lga Nsit_Ibom               = new Lga("AI029", "Nsit Ibom");
            Lga Uruan                   = new Lga("AI030", "Uruan");
            Lga Nsit_Atai               = new Lga("AI031", "Nsit Atai");
            Lga Aguata                  = new Lga("AN001", "Aguata");
            Lga Anambra_East            = new Lga("AN002", "Anambra East");
            Lga Anambra_West            = new Lga("AN003", "Anambra West");
            Lga Anaocha                 = new Lga("AN004", "Anaocha");
            Lga Awka_North              = new Lga("AN005", "Awka North");
            Lga Awka_South              = new Lga("AN006", "Awka South");
            Lga Ayamelum                = new Lga("AN007", "Ayamelum");
            Lga Dunukofia               = new Lga("AN008", "Dunukofia");
            Lga Ekwusigo                = new Lga("AN009", "Ekwusigo");
            Lga Idemili_North           = new Lga("AN010", "Idemili North");
            Lga Idemili_South           = new Lga("AN011", "Idemili South");
            Lga Ihiala                  = new Lga("AN012", "Ihiala");
            Lga Njikoka                 = new Lga("AN013", "Njikoka");
            Lga Nnewi_North             = new Lga("AN014", "Nnewi North");
            Lga Nnewi_South             = new Lga("AN015", "Nnewi South");
            Lga Ogbaru                  = new Lga("AN016", "Ogbaru");
            Lga Onitsha_North           = new Lga("AN017", "Onitsha North");
            Lga Onitsha_South           = new Lga("AN018", "Onitsha South");
            Lga Orumba_North            = new Lga("AN019", "Orumba North");
            Lga Orumba_South            = new Lga("AN020", "Orumba South");
            Lga Oyi                     = new Lga("AN021", "Oyi");
            Lga Dass                    = new Lga("BA006", "Dass");
            Lga Gamawa                  = new Lga("BA007", "Gamawa");
            Lga Ganjuwa                 = new Lga("BA008", "Ganjuwa");
            Lga Giade                   = new Lga("BA009", "Giade");
            Lga Itas_Gadau              = new Lga("BA010", "Itas/Gadau");
            Lga Jama_are                = new Lga("BA011", "Jama'are");
            Lga Ka_tagum                 = new Lga("BA0121", "Katagum");
            Lga Kirfi                   = new Lga("BA013", "Kirfi");
            Lga Misau                   = new Lga("BA014", "Misau");
            Lga Ningi                   = new Lga("BA015", "Ningi");
            Lga Shira                   = new Lga("BA016", "Shira");
            Lga Tafawa_Balewa           = new Lga("BA017", "Tafawa-Balewa");
            Lga Toro                    = new Lga("BA018", "Toro");
            Lga Warji                   = new Lga("BA019", "Warji");
            Lga Zaki                    = new Lga("BA020", "Zaki");
            Lga Bogoro                  = new Lga("BA021", "Bogoro");
            Lga War_ji                   = new Lga("BA0221", "Warji");
            Lga Alkaleri                = new Lga("BA023", "Alkaleri ");
            Lga Darazo                  = new Lga("BA024", "Darazo");
            Lga Gama_wa                  = new Lga("BA0251", "Gamawa");
            Lga Guma                    = new Lga("BN001", "Guma");
            Lga Makurdi                 = new Lga("BN002", "Makurdi");
            Lga Gwer_East               = new Lga("BN003", "Gwer East");
            Lga Tarka                   = new Lga("BN004", "Tarka");
            Lga Bukuru                  = new Lga("BN005", "Bukuru");
            Lga Gboko                   = new Lga("BN006", "Gboko");
            Lga Logo                    = new Lga("BN007", "Logo");
            Lga Katsina_Ala             = new Lga("BN008", "Katsina-Ala");
            Lga Ukum                    = new Lga("BN009", "Ukum");
            Lga Obi                     = new Lga("BN010", "Obi");
            Lga Konshisha               = new Lga("BN011", "Konshisha");
            Lga Ushongo                 = new Lga("BN012", "Ushongo");
            Lga Kwande                  = new Lga("BN013", "Kwande");
            Lga Oju                     = new Lga("BN014", "Oju");
            Lga Vandeikya               = new Lga("BN015", "Vandeikya");
            Lga Ohimini                 = new Lga("BN016", "Ohimini");
            Lga Agatu                   = new Lga("BN017", "Agatu");
            Lga Apa                     = new Lga("BN018", "Apa");
            Lga Gwer_West               = new Lga("BN019", "Gwer West");
            Lga Otukpa                  = new Lga("BN020", "Otukpa");
            Lga Ogbadibo                = new Lga("BN021", "Ogbadibo");
            Lga Okpokwu                 = new Lga("BN022", "Okpokwu");
            Lga Ado                     = new Lga("BN023", "Ado");
            Lga Abadam                  = new Lga("BR001", "Abadam");
            Lga Askira_Uba              = new Lga("BR002", "Askira/Uba");
            Lga Bama                    = new Lga("BR003", "Bama");
            Lga Bayo                    = new Lga("BR004", "Bayo");
            Lga Biu                     = new Lga("BR005", "Biu");
            Lga Chibok                  = new Lga("BR006", "Chibok");
            Lga Damboa                  = new Lga("BR007", "Damboa");
            Lga Dikwa                   = new Lga("BR008", "Dikwa");
            Lga Gubio                   = new Lga("BR009", "Gubio");
            Lga Guzamala                = new Lga("BR010", "Guzamala");
            Lga Gwoza                   = new Lga("BR011", "Gwoza");
            Lga Hawul                   = new Lga("BR012", "Hawul");
            Lga Jere                    = new Lga("BR013", "Jere");
            Lga Kaga                    = new Lga("BR014", "Kaga");
            Lga Kala_Balge              = new Lga("BR015", "Kala/Balge");
            Lga Konduga                 = new Lga("BR016", "Konduga");
            Lga Kukawa                  = new Lga("BR017", "Kukawa");
            Lga Kwaya_Kusar             = new Lga("BR018", "Kwaya Kusar");
            Lga Mafa                    = new Lga("BR019", "Mafa");
            Lga Magumeri                = new Lga("BR020", "Magumeri");
            Lga Maiduguri               = new Lga("BR021", "Maiduguri");
            Lga Marte                   = new Lga("BR022", "Marte");
            Lga Mobbar                  = new Lga("BR023", "Mobbar");
            Lga Monguno                 = new Lga("BR024", "Monguno");
            Lga Ngala                   = new Lga("BR025", "Ngala");
            Lga Nganzai                 = new Lga("BR026", "Nganzai");
            Lga Shani                   = new Lga("BR027", "Shani");
            Lga Kolokuma_Opokuma        = new Lga("BY001", "Kolokuma/Opokuma");
            Lga Yenegoa                 = new Lga("BY002", "Yenegoa");
            Lga Nembe                   = new Lga("BY003", "Nembe");
            Lga Ogbia                   = new Lga("BY004", "Ogbia");
            Lga Southern_Ijaw           = new Lga("BY005", "Southern Ijaw");
            Lga Brass                   = new Lga("BY006", "Brass");
            Lga Ekeremor                = new Lga("BY007", "Ekeremor");
            Lga Sagbama                 = new Lga("BY008", "Sagbama");
            Lga Patani                  = new Lga("BY009", "Patani");
            Lga Abi                     = new Lga("CR001", "Abi");
            Lga Akamkpa                 = new Lga("CR002", "Akamkpa");
            Lga Akpabuyo                = new Lga("CR003", "Akpabuyo");
            Lga Bekwarra                = new Lga("CR004", "Bekwarra");
            Lga Biase                   = new Lga("CR005", "Biase");
            Lga Boki                    = new Lga("CR006", "Boki");
            Lga Calabar_Municipal       = new Lga("CR007", "Calabar Municipal");
            Lga Calabar_South           = new Lga("CR008", "Calabar South");
            Lga Etung                   = new Lga("CR009", "Etung");
            Lga Ikom                    = new Lga("CR010", "Ikom");
            Lga Obanliku                = new Lga("CR011", "Obanliku");
            Lga Obubra                  = new Lga("CR012", "Obubra");
            Lga Obudu                   = new Lga("CR013", "Obudu");
            Lga Odukpani                = new Lga("CR014", "Odukpani");
            Lga Ogoja                   = new Lga("CR015", "Ogoja");
            Lga Yakurr                  = new Lga("CR016", "Yakurr");
            Lga Yala                    = new Lga("CR017", "Yala");
            Lga Aniocha_North           = new Lga("DE001", "Aniocha North");
            Lga Aniocha_South           = new Lga("DE002", "Aniocha South");
            Lga Bomadi                  = new Lga("DE003", "Bomadi");
            Lga Burutu                  = new Lga("DE004", "Burutu");
            Lga Ethiope_East            = new Lga("DE005", "Ethiope East");
            Lga Ethiope_West            = new Lga("DE006", "Ethiope West");
            Lga Ika_North_East          = new Lga("DE007", "Ika North East");
            Lga Ika_South               = new Lga("DE008", "Ika South");
            Lga Isoko_North             = new Lga("DE009", "Isoko North");
            Lga Isoko_South             = new Lga("DE010", "Isoko South");
            Lga Ndokwa_East             = new Lga("DE011", "Ndokwa East");
            Lga Ndokwa_West             = new Lga("DE012", "Ndokwa West");
            Lga O_kpe                    = new Lga("DE0131", "Okpe");
            Lga Oshimili_North          = new Lga("DE014", "Oshimili North");
            Lga Oshimili_South          = new Lga("DE015", "Oshimili South");
            Lga Pa_tani                  = new Lga("DE0161", "Patani");
            Lga Sapele                  = new Lga("DE017", "Sapele");
            Lga Udu                     = new Lga("DE018", "Udu");
            Lga Ughelli_North           = new Lga("DE019", "Ughelli North");
            Lga Ughelli_South           = new Lga("DE020", "Ughelli South");
            Lga Ukwuani                 = new Lga("DE021", "Ukwuani");
            Lga Uvwie                   = new Lga("DE022", "Uvwie");
            Lga Warri_North             = new Lga("DE023", "Warri North");
            Lga Warri_South             = new Lga("DE024", "Warri South");
            Lga Warri_South_West        = new Lga("DE025", "Warri South-West");
            Lga Abakaliki               = new Lga("EB001", "Abakaliki");
            Lga Afikpo_North            = new Lga("EB002", "Afikpo North");
            Lga Afikpo_South            = new Lga("EB003", "Afikpo South");
            Lga Ebonyi                  = new Lga("EB004", "Ebonyi");
            Lga Ezza_North              = new Lga("EB005", "Ezza North");
            Lga Ezza_South              = new Lga("EB006", "Ezza South");
            Lga Ikwo                    = new Lga("EB007", "Ikwo");
            Lga Ishielu                 = new Lga("EB008", "Ishielu");
            Lga Ivo                     = new Lga("EB009", "Ivo");
            Lga Izzi                    = new Lga("EB010", "Izzi");
            Lga Ohaozara                = new Lga("EB011", "Ohaozara");
            Lga Ohaukwu                 = new Lga("EB012", "Ohaukwu");
            Lga Onicha                  = new Lga("EB013", "Onicha");
            Lga Akoko_Edo               = new Lga("ED001", "Akoko-Edo");
            Lga Egor                    = new Lga("ED002", "Egor");
            Lga Esan_Central            = new Lga("ED003", "Esan Central");
            Lga Esan_North_East         = new Lga("ED004", "Esan North-East");
            Lga Esan_South_East         = new Lga("ED005", "Esan South-East");
            Lga Esan_West               = new Lga("ED006", "Esan West");
            Lga Etsako_Central          = new Lga("ED007", "Etsako Central");
            Lga Etsako_East             = new Lga("ED008", "Etsako East");
            Lga Etsako_West             = new Lga("ED009", "Etsako West");
            Lga Iguegben                = new Lga("ED010", "Iguegben");
            Lga Ikpoba_Okha             = new Lga("ED011", "Ikpoba-Okha");
            Lga Oredo                   = new Lga("ED012", "Oredo");
            Lga Orhionmwon              = new Lga("ED013", "Orhionmwon");
            Lga Ovia_North_East         = new Lga("ED014", "Ovia North-East");
            Lga Ovia_South_West         = new Lga("ED015", "Ovia South-West");
            Lga Owan_East               = new Lga("ED016", "Owan East");
            Lga Owan_West               = new Lga("ED017", "Owan West");
            Lga Uhunmwode               = new Lga("ED018", "Uhunmwode");
            Lga Ado_Ekiti               = new Lga("EK001", "Ado Ekiti");
            Lga Efon                    = new Lga("EK002", "Efon");
            Lga Ekiti_East              = new Lga("EK003", "Ekiti East");
            Lga Ekiti_South_West        = new Lga("EK004", "Ekiti South West");
            Lga Ekiti_West              = new Lga("EK005", "Ekiti West");
            Lga Emure                   = new Lga("EK006", "Emure");
            Lga Gbonyin                 = new Lga("EK007", "Gbonyin");
            Lga Ido_Osi                 = new Lga("EK008", "Ido-Osi");
            Lga Ijero                   = new Lga("EK009", "Ijero");
            Lga Ikere                   = new Lga("EK010", "Ikere");
            Lga Ikole                   = new Lga("EK011", "Ikole");
            Lga Ilejemeje               = new Lga("EK012", "Ilejemeje");
            Lga Irepodun_Ifelodun       = new Lga("EK013", "Irepodun/Ifelodun");
            Lga Ise_Orun                = new Lga("EK014", "Ise/Orun");
            Lga Moba                    = new Lga("EK015", "Moba");
            Lga Oye                     = new Lga("EK016", "Oye");
            Lga Aninri                  = new Lga("EN001", "Aninri");
            Lga Awgu                    = new Lga("EN002", "Awgu");
            Lga Enugu_East              = new Lga("EN003", "Enugu East");
            Lga Enugu_North             = new Lga("EN004", "Enugu North");
            Lga Enugu_South             = new Lga("EN005", "Enugu South");
            Lga Ezeagu                  = new Lga("EN006", "Ezeagu");
            Lga Igbo_Etiti              = new Lga("EN007", "Igbo-Etiti");
            Lga Igbo_Eze_North          = new Lga("EN008", "Igbo-Eze North");
            Lga Igbo_Eze_South          = new Lga("EN009", "Igbo-Eze South");
            Lga Isi_Uzo                 = new Lga("EN010", "Isi-Uzo");
            Lga Nkanu_East              = new Lga("EN011", "Nkanu East");
            Lga Nkanu_West              = new Lga("EN012", "Nkanu West");
            Lga Nsukka                  = new Lga("EN013", "Nsukka");
            Lga Oji_River               = new Lga("EN014", "Oji-River");
            Lga Udenu                   = new Lga("EN015", "Udenu");
            Lga Udi                     = new Lga("EN016", "Udi");
            Lga Uzo_Uwani               = new Lga("EN017", "Uzo-Uwani");
            Lga Abaji                   = new Lga("FC001", "Abaji");
            Lga Bwari                   = new Lga("FC002", "Bwari");
            Lga Gwagwalada              = new Lga("FC003", "Gwagwalada");
            Lga Kuje                    = new Lga("FC004", "Kuje");
            Lga Kwali                   = new Lga("FC005", "Kwali");
            Lga Municipal_Area_Council  = new Lga("FC006", "Municipal Area Council");
            Lga Akko                    = new Lga("GB001", "Akko");
            Lga Balanga                 = new Lga("GB002", "Balanga");
            Lga Billiri                 = new Lga("GB003", "Billiri");
            Lga Dukku                   = new Lga("GB004", "Dukku");
            Lga Funakaye                = new Lga("GB005", "Funakaye");
            Lga Gombe                   = new Lga("GB006", "Gombe");
            Lga Kaltungo                = new Lga("GB007", "Kaltungo");
            Lga Kwami                   = new Lga("GB008", "Kwami");
            Lga Nafada                  = new Lga("GB009", "Nafada");
            Lga Shomgom                 = new Lga("GB010", "Shomgom");
            Lga Yamaltu_Deba            = new Lga("GB011", "Yamaltu/Deba");
            Lga Aboh_Mbaise             = new Lga("IM001", "Aboh-Mbaise");
            Lga Ahiazu_Mbaise           = new Lga("IM002", "Ahiazu-Mbaise");
            Lga Ehime_Mbano             = new Lga("IM003", "Ehime-Mbano");
            Lga Ezinihitte              = new Lga("IM004", "Ezinihitte");
            Lga Ideato_North            = new Lga("IM005", "Ideato North");
            Lga Ideato_South            = new Lga("IM006", "Ideato South");
            Lga Ihitte_Uboma            = new Lga("IM007", "Ihitte/Uboma");
            Lga Ikeduru                 = new Lga("IM008", "Ikeduru");
            Lga Isiala_Mbano            = new Lga("IM009", "Isiala Mbano");
            Lga Isu                     = new Lga("IM010", "Isu");
            Lga Mbatoli                 = new Lga("IM011", "Mbatoli");
            Lga Ngor_Okpala             = new Lga("IM012", "Ngor-Okpala");
            Lga Njaba                   = new Lga("IM013", "Njaba");
            Lga Nkwerre                 = new Lga("IM014", "Nkwerre");
            Lga Nwangele                = new Lga("IM015", "Nwangele");
            Lga Obowo                   = new Lga("IM016", "Obowo");
            Lga Oguta                   = new Lga("IM017", "Oguta");
            Lga Ohaji_Egbema            = new Lga("IM018", "Ohaji/Egbema");
            Lga Okigwe                  = new Lga("IM019", "Okigwe");
            Lga Onuimo                  = new Lga("IM020", "Onuimo");
            Lga Orlu                    = new Lga("IM021", "Orlu");
            Lga Orsu                    = new Lga("IM022", "Orsu");
            Lga Oru_East                = new Lga("IM023", "Oru East");
            Lga Oru_West                = new Lga("IM024", "Oru West");
            Lga Owerri_Municipal        = new Lga("IM025", "Owerri Municipal");
            Lga Owerri_North            = new Lga("IM026", "Owerri North");
            Lga Owerri_West             = new Lga("IM027", "Owerri West");
            Lga Auyo                    = new Lga("JI001", "Auyo");
            Lga Babura                  = new Lga("JI002", "Babura");
            Lga Biriniwa                = new Lga("JI003", "Biriniwa");
            Lga Birnin_Kudu             = new Lga("JI004", "Birnin Kudu");
            Lga Buji                    = new Lga("JI005", "Buji");
            Lga Dutse                   = new Lga("JI006", "Dutse");
            Lga Gagarawa                = new Lga("JI007", "Gagarawa");
            Lga Garki                   = new Lga("JI008", "Garki");
            Lga Gumel                   = new Lga("JI009", "Gumel");
            Lga Guri                    = new Lga("JI010", "Guri");
            Lga Gwaram                  = new Lga("JI011", "Gwaram");
            Lga Gwiwa                   = new Lga("JI012", "Gwiwa");
            Lga Hadejia                 = new Lga("JI013", "Hadejia");
            Lga Jahun                   = new Lga("JI014", "Jahun");
            Lga Kafin_Hausa             = new Lga("JI015", "Kafin Hausa");
            Lga Kaugama                 = new Lga("JI016", "Kaugama");
            Lga Kazaure                 = new Lga("JI017", "Kazaure");
            Lga Kiri_Kasama             = new Lga("JI018", "Kiri Kasama");
            Lga Kiyawa                  = new Lga("JI019", "Kiyawa");
            Lga Maigatari               = new Lga("JI020", "Maigatari");
            Lga Malam_Madori            = new Lga("JI021", "Malam Madori");
            Lga Miga                    = new Lga("JI022", "Miga");
            Lga Ringim                  = new Lga("JI023", "Ringim");
            Lga Roni                    = new Lga("JI024", "Roni");
            Lga Sule_Tankarkar          = new Lga("JI025", "Sule Tankarkar");
            Lga Taura                   = new Lga("JI026", "Taura");
            Lga Yankwashi               = new Lga("JI027", "Yankwashi");
            Lga Aleiro                  = new Lga("KB001", "Aleiro");
            Lga Arewa_Dandi             = new Lga("KB002", "Arewa Dandi");
            Lga Argungu                 = new Lga("KB003", "Argungu");
            Lga Augie                   = new Lga("KB004", "Augie");
            Lga Bagudo                  = new Lga("KB005", "Bagudo");
            Lga Birnin_Kebbi            = new Lga("KB006", "Birnin Kebbi");
            Lga Bunza                   = new Lga("KB007", "Bunza");
            Lga Dandi                   = new Lga("KB008", "Dandi");
            Lga Fakai                   = new Lga("KB009", "Fakai");
            Lga Gwandu                  = new Lga("KB010", "Gwandu");
            Lga Jega                    = new Lga("KB011", "Jega");
            Lga Kalgo                   = new Lga("KB012", "Kalgo");
            Lga Koko_Besse              = new Lga("KB013", "Koko/Besse");
            Lga Maiyama                 = new Lga("KB014", "Maiyama");
            Lga Ngaski                  = new Lga("KB015", "Ngaski");
            Lga Sakaba                  = new Lga("KB016", "Sakaba");
            Lga Shanga                  = new Lga("KB017", "Shanga");
            Lga Suru_Zuru               = new Lga("KB018", "Suru (Zuru)");
            Lga Wasagu_Danko            = new Lga("KB019", "Wasagu/Danko");
            Lga Yauri                   = new Lga("KB020", "Yauri");
            Lga Zuru                    = new Lga("KB021", "Zuru");
            Lga Birnin_Gwari            = new Lga("KD001", "Birnin Gwari");
            Lga Chikun                  = new Lga("KD002", "Chikun");
            Lga Giwa                    = new Lga("KD003", "Giwa");
            Lga Igabi                   = new Lga("KD004", "Igabi");
            Lga Ikara                   = new Lga("KD005", "Ikara");
            Lga J_aba                    = new Lga("KD0061", "Jaba");
            Lga Jema_a                  = new Lga("KD007", "Jema'a");
            Lga Kachia                  = new Lga("KD008", "Kachia");
            Lga Kaduna_North            = new Lga("KD009", "Kaduna North");
            Lga Kaduna_South            = new Lga("KD010", "Kaduna South");
            Lga Kagarko                 = new Lga("KD011", "Kagarko");
            Lga Kajuru                  = new Lga("KD012", "Kajuru");
            Lga Kaura                   = new Lga("KD013", "Kaura");
            Lga kauru                   = new Lga("KD014", "kauru");
            Lga Kubau                   = new Lga("KD015", "Kubau");
            Lga Kudan                   = new Lga("KD016", "Kudan");
            Lga Lere                    = new Lga("KD017", "Lere");
            Lga Makarfi                 = new Lga("KD018", "Makarfi");
            Lga Sabon_Gari              = new Lga("KD019", "Sabon Gari");
            Lga Sanga                   = new Lga("KD020", "Sanga");
            Lga Soba                    = new Lga("KD021", "Soba");
            Lga Zangon_Kataf            = new Lga("KD022", "Zangon Kataf");
            Lga Zaria                   = new Lga("KD023", "Zaria");
            Lga Adavi                   = new Lga("KG001", "Adavi");
            Lga Ajaokuta                = new Lga("KG002", "Ajaokuta");
            Lga Ankpa                   = new Lga("KG003", "Ankpa");
            Lga Bassa                   = new Lga("KG004", "Bassa");
            Lga Dekina                  = new Lga("KG005", "Dekina");
            Lga Ibaji                   = new Lga("KG006", "Ibaji");
            Lga Idah                    = new Lga("KG007", "Idah");
            Lga Igalamela_Odolu         = new Lga("KG008", "Igalamela-Odolu");
            Lga Ijumu                   = new Lga("KG009", "Ijumu");
            Lga Kabba_Bunu              = new Lga("KG010", "Kabba/Bunu");
            Lga Kogi                    = new Lga("KG011", "Kogi");
            Lga Lokoja                  = new Lga("KG012", "Lokoja");
            Lga Mopa_Muro               = new Lga("KG013", "Mopa-Muro");
            Lga Ofu                     = new Lga("KG014", "Ofu");
            Lga Ogori_Magongo           = new Lga("KG015", "Ogori/Magongo");
            Lga Okehi                   = new Lga("KG016", "Okehi");
            Lga Okene                   = new Lga("KG017", "Okene");
            Lga Olamaboro               = new Lga("KG018", "Olamaboro");
            Lga Omala                   = new Lga("KG019", "Omala");
            Lga Yagba_East              = new Lga("KG020", "Yagba East");
            Lga Yagba_West              = new Lga("KG021", "Yagba West");
            Lga Ajingi                  = new Lga("KN001", "Ajingi");
            Lga Albasu                  = new Lga("KN002", "Albasu");
            Lga Bagwai                  = new Lga("KN003", "Bagwai");
            Lga Bebeji                  = new Lga("KN004", "Bebeji");
            Lga Bichi                   = new Lga("KN005", "Bichi");
            Lga Bunkure                 = new Lga("KN006", "Bunkure");
            Lga Dala                    = new Lga("KN007", "Dala");
            Lga Dambatta                = new Lga("KN008", "Dambatta");
            Lga Dawakin_Kudu            = new Lga("KN009", "Dawakin Kudu");
            Lga Dawakin_Tofa            = new Lga("KN010", "Dawakin Tofa");
            Lga Doguwa                  = new Lga("KN011", "Doguwa");
            Lga Fagge                   = new Lga("KN012", "Fagge");
            Lga Gabasawa                = new Lga("KN013", "Gabasawa");
            Lga Garko                   = new Lga("KN014", "Garko");
            Lga Garum_Mallam            = new Lga("KN015", "Garum Mallam");
            Lga Gaya                    = new Lga("KN016", "Gaya");
            Lga Gezawa                  = new Lga("KN017", "Gezawa");
            Lga Gwale                   = new Lga("KN018", "Gwale");
            Lga Gwarzo                  = new Lga("KN019", "Gwarzo");
            Lga Kabo                    = new Lga("KN020", "Kabo");
            Lga Kano_Municipal          = new Lga("KN021", "Kano Municipal");
            Lga Karaye                  = new Lga("KN022", "Karaye");
            Lga Kibiya                  = new Lga("KN023", "Kibiya");
            Lga Kiru                    = new Lga("KN024", "Kiru");
            Lga Kumbotso                = new Lga("KN025", "Kumbotso");
            Lga Kunchi                  = new Lga("KN026", "Kunchi");
            Lga Kura                    = new Lga("KN027", "Kura");
            Lga Madobi                  = new Lga("KN028", "Madobi");
            Lga Makoda                  = new Lga("KN029", "Makoda");
            Lga Minjibir                = new Lga("KN030", "Minjibir");
            Lga Nassarawa_Kano          = new Lga("KN031", "Nassarawa, Kano");
            Lga Rano                    = new Lga("KN032", "Rano");
            Lga Rimin_Gado              = new Lga("KN033", "Rimin Gado");
            Lga Rogo                    = new Lga("KN034", "Rogo");
            Lga Shanono                 = new Lga("KN035", "Shanono");
            Lga Sumaila                 = new Lga("KN036", "Sumaila");
            Lga Takai                   = new Lga("KN037", "Takai");
            Lga Tarauni                 = new Lga("KN038", "Tarauni");
            Lga Tofa                    = new Lga("KN039", "Tofa");
            Lga Tsanyawa                = new Lga("KN040", "Tsanyawa");
            Lga Tudun_Wada              = new Lga("KN041", "Tudun Wada");
            Lga Ungongo                 = new Lga("KN042", "Ungongo");
            Lga Warawa                  = new Lga("KN043", "Warawa");
            Lga Wudil                   = new Lga("KN044", "Wudil");
            Lga Bakori                  = new Lga("KT001", "Bakori");
            Lga Batagarawa              = new Lga("KT002", "Batagarawa");
            Lga Batsari                 = new Lga("KT003", "Batsari");
            Lga Baure                   = new Lga("KT004", "Baure");
            Lga Bindawa                 = new Lga("KT005", "Bindawa");
            Lga Charanchi               = new Lga("KT006", "Charanchi");
            Lga Dan_Musa                = new Lga("KT007", "Dan Musa");
            Lga Dandume                 = new Lga("KT008", "Dandume");
            Lga Danja                   = new Lga("KT009", "Danja");
            Lga Daura                   = new Lga("KT010", "Daura");
            Lga Dutsi                   = new Lga("KT011", "Dutsi");
            Lga Dutsin_Ma               = new Lga("KT012", "Dutsin Ma");
            Lga Faskari                 = new Lga("KT013", "Faskari");
            Lga Funtua                  = new Lga("KT014", "Funtua");
            Lga Ingawa                  = new Lga("KT015", "Ingawa");
            Lga Jibia                   = new Lga("KT016", "Jibia");
            Lga Kafur                   = new Lga("KT017", "Kafur");
            Lga Kaita                   = new Lga("KT018", "Kaita");
            Lga Kankara                 = new Lga("KT019", "Kankara");
            Lga Kankia                  = new Lga("KT020", "Kankia");
            Lga Katsina                 = new Lga("KT021", "Katsina");
            Lga Kurfi                   = new Lga("KT022", "Kurfi");
            Lga Kusada                  = new Lga("KT023", "Kusada");
            Lga Mai_adua                = new Lga("KT024", "Mai'adua");
            Lga Malumfashi              = new Lga("KT025", "Malumfashi");
            Lga Mani                    = new Lga("KT026", "Mani");
            Lga Mashi                   = new Lga("KT027", "Mashi");
            Lga Matazu                  = new Lga("KT028", "Matazu");
            Lga Musawa                  = new Lga("KT029", "Musawa");
            Lga Rimi                    = new Lga("KT030", "Rimi");
            Lga Sabuwa                  = new Lga("KT031", "Sabuwa");
            Lga Safana                  = new Lga("KT032", "Safana");
            Lga Sandamu                 = new Lga("KT033", "Sandamu");
            Lga Zango                   = new Lga("KT034", "Zango");
            Lga Asa                     = new Lga("KW001", "Asa");
            Lga Baruten                 = new Lga("KW002", "Baruten");
            Lga Edu                     = new Lga("KW003", "Edu");
            Lga Ekiti                   = new Lga("KW004", "Ekiti");
            Lga Ifelodun_Kwara          = new Lga("KW004", "Ifelodun_Kwara");
            Lga Ilorin_East             = new Lga("KW006", "Ilorin East");
            Lga Ilorin_South            = new Lga("KW007", "Ilorin South");
            Lga Ilorin_West             = new Lga("KW008", "Ilorin West");
            Lga Irepodun_Kwara          = new Lga("KW009", "Irepodun, Kwara");
            Lga Isin                    = new Lga("KW010", "Isin");
            Lga Kaiama                  = new Lga("KW011", "Kaiama");
            Lga Moro                    = new Lga("KW012", "Moro");
            Lga Offa                    = new Lga("KW013", "Offa");
            Lga Oke_Ero                 = new Lga("KW014", "Oke Ero");
            Lga Oyun                    = new Lga("KW015", "Oyun");
            Lga Pategi                  = new Lga("KW016", "Pategi");
            Lga Epe                     = new Lga("LA001", "Epe");
            Lga Ibeju_Lekki             = new Lga("LA002", "Ibeju Lekki");
            Lga Eti_Osa                 = new Lga("LA003", "Eti Osa");
            Lga Lagos_Island            = new Lga("LA004", "Lagos Island");
            Lga Amuwo_Odofin            = new Lga("LA005", "Amuwo Odofin");
            Lga Apapa                   = new Lga("LA006", "Apapa");
            Lga Ajeromi_Ifelodun        = new Lga("LA007", "Ajeromi/Ifelodun");
            Lga Badagry                 = new Lga("LA008", "Badagry");
            Lga Ojo                     = new Lga("LA009", "Ojo");
            Lga Oshodi_Isolo            = new Lga("LA010", "Oshodi/Isolo");
            Lga Alimosho                = new Lga("LA011", "Alimosho");
            Lga Agege                   = new Lga("LA012", "Agege");
            Lga Ifako_Ijaye             = new Lga("LA013", "Ifako/Ijaye");
            Lga Mushin                  = new Lga("LA014", "Mushin");
            Lga Ikeja                   = new Lga("LA015", "Ikeja");
            Lga Surulere                = new Lga("LA016", "Surulere");
            Lga Shomolu                 = new Lga("LA017", "Shomolu");
            Lga Lagos_Mainland          = new Lga("LA018", "Lagos Mainland");
            Lga Ikorodu                 = new Lga("LA019", "Ikorodu");
            Lga Kosofe                  = new Lga("LA020", "Kosofe");
            Lga Akwanga                 = new Lga("NA001", "Akwanga");
            Lga Nassarawa_Egon          = new Lga("NA002", "Nassarawa Egon");
            Lga Wamba                   = new Lga("NA003", "Wamba");
            Lga Karu                    = new Lga("NA004", "Karu");
            Lga Keffi                   = new Lga("NA005", "Keffi");
            Lga Kokona                  = new Lga("NA006", "Kokona");
            Lga Doma                    = new Lga("NA007", "Doma");
            Lga Lafia                   = new Lga("NA008", "Lafia");
            Lga Nassarawa               = new Lga("NA009", "Nassarawa");
            Lga Toto                    = new Lga("NA010", "Toto");
            Lga Keana                   = new Lga("NA011", "Keana");
            Lga Awe                     = new Lga("NA012", "Awe");
            Lga O_bi                     = new Lga("NA0131", "Obi");
            Lga Agaie                   = new Lga("NG001", "Agaie");
            Lga Agwara                  = new Lga("NG002", "Agwara");
            Lga Bida                    = new Lga("NG003", "Bida");
            Lga Borgu                   = new Lga("NG004", "Borgu");
            Lga Bosso                   = new Lga("NG005", "Bosso");
            Lga Chanchaga               = new Lga("NG006", "Chanchaga");
            Lga Edati                   = new Lga("NG007", "Edati");
            Lga Gbako                   = new Lga("NG008", "Gbako");
            Lga Gurara                  = new Lga("NG009", "Gurara");
            Lga Katcha                  = new Lga("NG010", "Katcha");
            Lga Kontagora               = new Lga("NG011", "Kontagora");
            Lga Lapai                   = new Lga("NG012", "Lapai");
            Lga Lavun                   = new Lga("NG013", "Lavun");
            Lga Magama                  = new Lga("NG014", "Magama");
            Lga Mairiga                 = new Lga("NG015", "Mairiga");
            Lga Mashegu                 = new Lga("NG016", "Mashegu");
            Lga Mokwa                   = new Lga("NG017", "Mokwa");
            Lga Muya                    = new Lga("NG018", "Muya");
            Lga Paikoro                 = new Lga("NG019", "Paikoro");
            Lga Rafi                    = new Lga("NG020", "Rafi");
            Lga Rijau                   = new Lga("NG021", "Rijau");
            Lga Shiroro                 = new Lga("NG022", "Shiroro");
            Lga Suleja                  = new Lga("NG023", "Suleja");
            Lga Tafa                    = new Lga("NG024", "Tafa");
            Lga Wushishi                = new Lga("NG025", "Wushishi");
            Lga Ifedore                 = new Lga("OD001", "Ifedore");
            Lga Ile_Oluji_Okeigbo       = new Lga("OD002", "Ile Oluji/Okeigbo");
            Lga Akure_North             = new Lga("OD003", "Akure North");
            Lga Akure_South             = new Lga("OD004", "Akure South");
            Lga Ose                     = new Lga("OD005", "Ose");
            Lga Owo                     = new Lga("OD006", "Owo");
            Lga Akoko_North_West        = new Lga("OD007", "Akoko North West");
            Lga Akoko_North_East        = new Lga("OD008", "Akoko North East");
            Lga Akoko_South_East        = new Lga("OD009", "Akoko South East");
            Lga Akoko_South_West        = new Lga("OD010", "Akoko South West");
            Lga Idanre                  = new Lga("OD011", "Idanre");
            Lga Ondo_East               = new Lga("OD012", "Ondo East");
            Lga Ondo_West               = new Lga("OD013", "Ondo West");
            Lga Odigbo                  = new Lga("OD014", "Odigbo");
            Lga Ese_Odo                 = new Lga("OD015", "Ese Odo");
            Lga Ilaje                   = new Lga("OD016", "Ilaje");
            Lga Okitipupa               = new Lga("OD017", "Okitipupa");
            Lga Irele                   = new Lga("OD018", "Irele");
            Lga Imeko_Afon              = new Lga("OG001", "Imeko Afon");
            Lga Abeokuta_South          = new Lga("OG002", "Abeokuta South");
            Lga Abeokuta_North          = new Lga("OG003", "Abeokuta North");
            Lga Egbado_North            = new Lga("OG004", "Egbado North");
            Lga Egbado_South            = new Lga("OG005", "Egbado South");
            Lga Ikenne                  = new Lga("OG006", "Ikenne");
            Lga Shagamu                 = new Lga("OG007", "Shagamu");
            Lga Ipokia                  = new Lga("OG008", "Ipokia");
            Lga Ado_Odo_Otta            = new Lga("OG009", "Ado Odo/Otta");
            Lga Ewekoro                 = new Lga("OG010", "Ewekoro");
            Lga Ifo                     = new Lga("OG011", "Ifo");
            Lga Odeda                   = new Lga("OG012", "Odeda");
            Lga Obafemi_Owode           = new Lga("OG013", "Obafemi Owode");
            Lga Ogun_waterside          = new Lga("OG014", "Ogun waterside");
            Lga Ijebu_East              = new Lga("OG015", "Ijebu East");
            Lga Ijebu_ode               = new Lga("OG016", "Ijebu ode");
            Lga Remo_North              = new Lga("OG017", "Remo North");
            Lga Ijebu_North             = new Lga("OG018", "Ijebu North");
            Lga Ijebu_North_East        = new Lga("OG019", "Ijebu North East");
            Lga Odogbolu                = new Lga("OG020", "Odogbolu");
            Lga Aiyedaade               = new Lga("OS001", "Aiyedaade");
            Lga Aiyedire                = new Lga("OS002", "Aiyedire");
            Lga Atakunmosa_East         = new Lga("OS003", "Atakunmosa East");
            Lga Atakunmosa_West         = new Lga("OS004", "Atakunmosa West");
            Lga Boluwaduro              = new Lga("OS005", "Boluwaduro");
            Lga Boripe                  = new Lga("OS006", "Boripe");
            Lga Ede_North               = new Lga("OS007", "Ede North");
            Lga Ede_South               = new Lga("OS008", "Ede South");
            Lga Egbedore                = new Lga("OS009", "Egbedore");
            Lga Ejigbo                  = new Lga("OS010", "Ejigbo");
            Lga Ife_Cen_tral             = new Lga("OS0111", "Ife Central");
            Lga Ife_East                = new Lga("OS012", "Ife East");
            Lga Ife_North               = new Lga("OS013", "Ife North");
            Lga Ife_South               = new Lga("OS014", "Ife South");
            Lga Ifedayo                 = new Lga("OS015", "Ifedayo");
            Lga Ife_lodun                = new Lga("OS0161", "Ifelodun");
            Lga Ila                     = new Lga("OS017", "Ila");
            Lga Ilesha_East             = new Lga("OS018", "Ilesha East");
            Lga Ilesha_West             = new Lga("OS019", "Ilesha West");
            Lga Irepodun                = new Lga("OS020", "Irepodun");
            Lga Irewole                 = new Lga("OS021", "Irewole");
            Lga Isokan                  = new Lga("OS022", "Isokan");
            Lga Iwo                     = new Lga("OS023", "Iwo");
            Lga Obokun                  = new Lga("OS024", "Obokun");
            Lga Odo_Otin                = new Lga("OS025", "Odo Otin");
            Lga Ola_oluwa               = new Lga("OS026", "Ola oluwa");
            Lga Olorunda                = new Lga("OS027", "Olorunda");
            Lga Oriade                  = new Lga("OS028", "Oriade");
            Lga Orolu                   = new Lga("OS029", "Orolu");
            Lga Osogbo                  = new Lga("OS030", "Osogbo");
            Lga Ibadan_North_East       = new Lga("OY001", "Ibadan North East");
            Lga Ibadan_South_West       = new Lga("OY002", "Ibadan South West");
            Lga Ibadan_South_East       = new Lga("OY003", "Ibadan South East");
            Lga Ido                     = new Lga("OY004", "Ido");
            Lga Afijio                  = new Lga("OY005", "Afijio");
            Lga Akinyele                = new Lga("OY006", "Akinyele");
            Lga Egbeda                  = new Lga("OY007", "Egbeda");
            Lga Oluyole                 = new Lga("OY008", "Oluyole");
            Lga Ona_ara                 = new Lga("OY009", "Ona ara");
            Lga Lagelu                  = new Lga("OY010", "Lagelu");
            Lga Ogo_Oluwa               = new Lga("OY011", "Ogo Oluwa");
            Lga Suru_lere                = new Lga("OY0121", "Surulere");
            Lga Ogbomosho_North         = new Lga("OY013", "Ogbomosho North");
            Lga Ogbomosho_South         = new Lga("OY014", "Ogbomosho South");
            Lga Atisbo                  = new Lga("OY015", "Atisbo");
            Lga Irepo                   = new Lga("OY016", "Irepo");
            Lga Orelope                 = new Lga("OY017", "Orelope");
            Lga Saki_West               = new Lga("OY018", "Saki West");
            Lga Saki_East               = new Lga("OY019", "Saki East");
            Lga Atiba                   = new Lga("OY020", "Atiba");
            Lga Iwajowa                 = new Lga("OY021", "Iwajowa");
            Lga Kajola                  = new Lga("OY022", "Kajola");
            Lga Itesiwaju               = new Lga("OY023", "Itesiwaju");
            Lga Ori_Ire                 = new Lga("OY024", "Ori Ire");
            Lga Olorunsogo              = new Lga("OY025", "Olorunsogo");
            Lga Ibarapa_Central         = new Lga("OY026", "Ibarapa Central");
            Lga Ibarapa_East            = new Lga("OY027", "Ibarapa East");
            Lga Ibarapa_North           = new Lga("OY028", "Ibarapa North");
            Lga Iseyin                  = new Lga("OY029", "Iseyin");
            Lga Oyo_East                = new Lga("OY030", "Oyo East");
            Lga Oyo_West                = new Lga("OY031", "Oyo West");
            Lga Ibadan_North_West       = new Lga("OY032", "Ibadan North West");
            Lga Ibadan_North            = new Lga("OY033", "Ibadan North ");
            Lga Mangu                   = new Lga("PL001", "Mangu");
            Lga Quaan_Pan               = new Lga("PL002", "Qua'an Pan");
            Lga Bokkos                  = new Lga("PL003", "Bokkos");
            Lga Riyom                   = new Lga("PL004", "Riyom");
            Lga Barkin_Ladi             = new Lga("PL005", "Barkin Ladi");
            Lga Pank_shin                = new Lga("PL0061", "Pankshin");
            Lga Kanam                   = new Lga("PL007", "Kanam");
            Lga Kanke                   = new Lga("PL008", "Kanke");
            Lga Jos_North               = new Lga("PL009", "Jos North");
            Lga Jos_South               = new Lga("PL010", "Jos South");
            Lga Jos_East                = new Lga("PL011", "Jos East");
            Lga Bas_sa                   = new Lga("PL0121","Bassa");
            Lga Mikang                  = new Lga("PL013", "Mikang");
            Lga Shendam                 = new Lga("PL014", "Shendam");
            Lga Langtang_North          = new Lga("PL015", "Langtang North");
            Lga Langtang_South          = new Lga("PL016", "Langtang South");
            Lga Wase                    = new Lga("PL017", "Wase");
            Lga Abua_Odual              = new Lga("RV001", "Abua/Odual");
            Lga Ahoada_East             = new Lga("RV002", "Ahoada East");
            Lga Ahoada_West             = new Lga("RV003", "Ahoada West");
            Lga Akuku_Toru              = new Lga("RV004", "Akuku Toru");
            Lga Andoni                  = new Lga("RV005", "Andoni");
            Lga Asari_Toru              = new Lga("RV006", "Asari-Toru");
            Lga Bonny                   = new Lga("RV007", "Bonny");
            Lga Degema                  = new Lga("RV008", "Degema");
            Lga Eleme                   = new Lga("RV009", "Eleme");
            Lga Emuoha                  = new Lga("RV010", "Emuoha");
            Lga Etche                   = new Lga("RV011", "Etche");
            Lga Gokana                  = new Lga("RV012", "Gokana");
            Lga Ikwerre                 = new Lga("RV013", "Ikwerre");
            Lga Khana                   = new Lga("RV014", "Khana");
            Lga Obio_Akpor              = new Lga("RV015", "Obio/Akpor");
            Lga Ogba_Egbema_Ndoni       = new Lga("RV016", "Ogba/Egbema/Ndoni");
            Lga Ogu_Bolo                = new Lga("RV017", "Ogu Bolo");
            Lga Okrika                  = new Lga("RV018", "Okrika");
            Lga Omumma                  = new Lga("RV019", "Omumma");
            Lga Opobo_Nkoro             = new Lga("RV020", "Opobo_Nkoro");
            Lga Oyigbo                  = new Lga("RV021", "Oyigbo");
            Lga Port_Harcourt           = new Lga("RV021", "Port_Harcourt");
            Lga Tai                     = new Lga("RV023", "Tai");
            Lga Binji                   = new Lga("SK001", "Binji       ");
            Lga Bodinga                 = new Lga("SK002", "Bodinga     ");
            Lga Dange_Shuni             = new Lga("SK003", "Dange_Shuni ");
            Lga Gada                    = new Lga("SK004", "Gada        ");
            Lga Goronyo                 = new Lga("SK005", "Goronyo     ");
            Lga Gudu                    = new Lga("SK006", "Gudu        ");
            Lga Gwadabawa               = new Lga("SK007", "Gwadabawa   ");
            Lga Illela                  = new Lga("SK008", "Illela      ");
            Lga Isa                     = new Lga("SK009", "Isa         ");
            Lga Kebbe                   = new Lga("SK010", "Kebbe       ");
            Lga Kware                   = new Lga("SK011", "Kware       ");
            Lga Rabah                   = new Lga("SK012", "Rabah       ");
            Lga Sabon_Birni             = new Lga("SK013", "Sabon_Birni ");
            Lga Shagari                 = new Lga("SK014", "Shagari     ");
            Lga Silame                  = new Lga("SK015", "Silame      ");
            Lga Sokoto_North                  = new Lga("SK016", "Sokoto_North");
            Lga Sokoto_South                  = new Lga("SK017", "Sokoto_South");
            Lga Tambuwal                  = new Lga("SK018", "Tambuwal    ");
            Lga Tangaza                  = new Lga("SK019", "Tangaza     ");
            Lga Tureta                  = new Lga("SK020", "Tureta      ");
            Lga Wamako                  = new Lga("SK021", "Wamako      ");
            Lga Wurno                  = new Lga("SK022", "Wurno       ");
            Lga Yabo                  = new Lga("SK023", "Yabo        ");
            Lga Ardo_Kola                  = new Lga("TR001", "Ardo_Kola   ");
            Lga Bali                  = new Lga("TR002", "Bali        ");
            Lga Donga                  = new Lga("TR003", "Donga       ");
            Lga Gashaka                  = new Lga("TR004", "Gashaka     ");
            Lga Gassol                  = new Lga("TR005", "Gassol      ");
            Lga Ibi                  = new Lga("TR006", "Ibi         ");
            Lga Jalingo                  = new Lga("TR007", "Jalingo     ");
            Lga Karim_Lamido                  = new Lga("TR008", "Karim_Lamido");
            Lga Kurmi                  = new Lga("TR009", "Kurmi    ");
            Lga Lau                  = new Lga("TR010", "Lau      ");
            Lga Sardauna                  = new Lga("TR011", "Sardauna ");
            Lga Takum                  = new Lga("TR012", "Takum    ");
            Lga Ussa                  = new Lga("TR013", "Ussa     ");
            Lga Wukari                  = new Lga("TR014", "Wukari   ");
            Lga Yorro                  = new Lga("TR015", "Yorro    ");
            Lga Zing                  = new Lga("TR016", "Zing     ");
            Lga Barde                  = new Lga("YB001", "Barde    ");
            Lga Bursari                  = new Lga("YB002", "Bursari  ");
            Lga Damaturu                  = new Lga("YB003", "Damaturu ");
            Lga Fika                  = new Lga("YB004", "Fika     ");
            Lga Fune                  = new Lga("YB005", "Fune     ");
            Lga Geidam                  = new Lga("YB006", "Geidam   ");
            Lga Gujba                  = new Lga("YB007", "Gujba    ");
            Lga Gulani                  = new Lga("YB008", "Gulani   ");
            Lga Jakusko                  = new Lga("YB009", "Jakusko  ");
            Lga Karasuwa                  = new Lga("YB010", "Karasuwa ");
            Lga Machina                  = new Lga("YB011", "Machina  ");
            Lga Nangere                  = new Lga("YB012", "Nangere  ");
            Lga Nguru                  = new Lga("YB013", "Nguru    ");
            Lga Potiskum                  = new Lga("YB014", "Potiskum ");
            Lga Tarmuwa                  = new Lga("YB015", "Tarmuwa"  );
            Lga Yunusari                  = new Lga("YB016", "Yunusari ");
            Lga Yusufari                  = new Lga("YB017", "Yusufari ");
            Lga Anka                  = new Lga("ZM001", "Anka     ");
            Lga Bakura                  = new Lga("ZM002", "Bakura   ");
            Lga Birnin_Magaji_Kiyaw                  = new Lga("ZM003", "Birnin_Magaji_Kiyaw");
            Lga Bukkuyum                  = new Lga("ZM004", "Bukkuyum     ");
            Lga Bungudu                  = new Lga("ZM005", "Bungudu      ");
            Lga Gummi                  = new Lga("ZM005", "Gummi");
            Lga Gusau                  = new Lga("ZM005", "Gusau");
            Lga Kaura_Namoda                  = new Lga("ZM008", "Kaura_Namoda ");
            Lga Maradun                  = new Lga("ZM009", "Maradun      ");
            Lga Maru                  = new Lga("ZM010", "Maru         ");
            Lga Shinkafi                  = new Lga("ZM011", "Shinkafi     ");
            Lga Talata_Mafara                  = new Lga("ZM011", "Talata_Mafara");
            Lga Tsafe                  = new Lga("ZM011", "Tsafe");
            Lga Zurmi                  = new Lga("ZM014", "Zurmi");







            List<Lga> list = new ArrayList<>();
            list.add(Aba_North);
            list.add(Aba_South  );
            list.add(Arochukwu  );
            list.add(Bende      );
            list.add(Ikwauano   );
            list.add(Isiala_Ngwa_North);
            list.add(Isiala_Ngwa_South);
            list.add(Isuikwuato       );
            list.add(Obi_Ngwa         );
            list.add(Ohafia           );
            list.add(Osisioma_Ngwa    );
            list.add(Ugwunagbo        );
            list.add(Ukwa_East        );
            list.add(Ukwa_West        );
            list.add(Umuahia_North    );
            list.add(Umuahia_South    );
            list.add(Umu_Nneochi      );
            list.add(Demsa            );
            list.add(Fufore           );
            list.add(Ganye            );
            list.add(Girie            );
            list.add(Gombi            );
            list.add(Guyuk            );
            list.add(Hong             );
            list.add(Jada             );
            list.add(Larmurde         );
            list.add(Madagali         );
            list.add(Maiha            );
            list.add(Mayo_Belwa       );
            list.add(Michika          );
            list.add(Mubi_North       );
            list.add(Mubi_South       );
            list.add(Numan            );
            list.add(Shelleng         );
            list.add(Song             );
            list.add(Teungo           );
            list.add(Yola_North       );
            list.add(Yola_South       );
            list.add(Eket             );
            list.add(Onna             );
            list.add(Nsit_Ubium       );
            list.add(Etinan           );
            list.add(Mkpat_Enin       );
            list.add(Uyo              );
            list.add(Ibiono_Ibom      );
            list.add(Itu              );
            list.add(Urue_Offong_Oruko);
            list.add(Okobo           );
            list.add(Oron            );
            list.add(Etim_Ekpo       );
            list.add(Ika             );
            list.add(Abak            );
            list.add(Ini             );
            list.add(Essien_Udim     );
            list.add(Ikono           );
            list.add(Ikot_Ekpene     );
            list.add(Obot_Akare      );
            list.add(Uka_Nafun       );
            list.add(Esit_Eket       );
            list.add(Mbo             );
            list.add(Eastern_Obolo   );
            list.add(Ibeno           );
            list.add(Ikot_Abasi      );
            list.add(Udung_Uko       );
            list.add(Oruk_Anam       );
            list.add(Ibesikpo_Asutan );
            list.add(Nsit_Ibom    );
            list.add(Uruan        );
            list.add(Nsit_Atai    );
            list.add(Aguata       );
            list.add(Anambra_East );
            list.add(Anambra_West );
            list.add(Anaocha      );
            list.add(Awka_North   );
            list.add(Awka_South   );
            list.add(Ayamelum     );
            list.add(Dunukofia    );
            list.add(Ekwusigo     );
            list.add(Idemili_North);
            list.add(Idemili_South);
            list.add(Ihiala       );
            list.add(Njikoka      );
            list.add(Nnewi_North  );
            list.add(Nnewi_South  );
            list.add(Ogbaru       );
            list.add(Onitsha_North);
            list.add(Onitsha_South);
            list.add(Orumba_North );
            list.add(Orumba_South );
            list.add(Oyi          );
            list.add(Dass         );
            list.add(Gamawa       );
            list.add(Ganjuwa      );
            list.add(Giade        );
            list.add(Itas_Gadau   );
            list.add(Jama_are     );
            list.add(Ka_tagum     );
            list.add(Kirfi        );
            list.add(Misau        );
            list.add(Ningi        );
            list.add(Shira        );
            list.add(Tafawa_Balewa);
            list.add(Toro       );
            list.add(Warji      );
            list.add(Zaki       );
            list.add(Bogoro     );
            list.add(War_ji     );
            list.add(Alkaleri   );
            list.add(Darazo     );
            list.add(Gama_wa    );
            list.add(Guma       );
            list.add(Makurdi    );
            list.add(Gwer_East  );
            list.add(Tarka      );
            list.add(Bukuru     );
            list.add(Gboko      );
            list.add(Logo       );
            list.add(Katsina_Ala);
            list.add(Ukum     );
            list.add(Obi      );
            list.add(Konshisha);
            list.add(Ushongo  );
            list.add(Kwande   );
            list.add(Oju      );
            list.add(Vandeikya);
            list.add(Ohimini  );
            list.add(Agatu    );
            list.add(Apa      );
            list.add(Gwer_West);
            list.add(Otukpa  );
            list.add(Ogbadibo);
            list.add( Okpokwu);
            list.add( Ado    );
            list.add(Abadam);
            list.add(Askira_Uba         );
            list.add(Bama               );
            list.add(Bayo               );
            list.add(Biu                );
            list.add(Chibok             );
            list.add(Damboa             );
            list.add(Dikwa              );
            list.add(Gubio              );
            list.add(Guzamala           );
            list.add(Gwoza              );
            list.add(Hawul              );
            list.add(Jere               );
            list.add(Kaga               );
            list.add(Kala_Balge         );
            list.add(Konduga            );
            list.add(Kukawa             );
            list.add(Kwaya_Kusar        );
            list.add(Mafa               );
            list.add(Magumeri           );
            list.add(Maiduguri          );
            list.add(Marte              );
            list.add(Mobbar             );
            list.add(Monguno            );
            list.add(Ngala              );
            list.add(Nganzai            );
            list.add(Shani              );
            list.add(Kolokuma_Opokuma   );
            list.add(Yenegoa            );
            list.add(Nembe              );
            list.add(Ogbia              );
            list.add(Southern_Ijaw      );
            list.add(Brass              );
            list.add(Ekeremor           );
            list.add(Sagbama            );
            list.add(Patani             );
            list.add(Abi                );
            list.add(Akamkpa            );
            list.add(Akpabuyo           );
            list.add(Bekwarra           );
            list.add(Biase              );
            list.add(Boki               );
            list.add(Calabar_Municipal  );
            list.add(Calabar_South      );
            list.add(Etung              );
            list.add(Ikom               );
            list.add(Obanliku           );
            list.add(Obubra             );
            list.add(Obudu              );
            list.add(Odukpani           );
            list.add(Ogoja              );
            list.add(Yakurr             );
            list.add(Yala               );
            list.add(Aniocha_North      );
            list.add(Aniocha_South      );
            list.add(Bomadi             );
            list.add(Burutu             );
            list.add(Ethiope_East       );
            list.add(Ethiope_West       );
            list.add(Ika_North_East     );
            list.add(Ika_South          );
            list.add(Isoko_North        );
            list.add(Isoko_South        );
            list.add(Ndokwa_East        );
            list.add(Ndokwa_West        );
            list.add(O_kpe              );
            list.add(Oshimili_North     );
            list.add(Oshimili_South     );
            list.add(Pa_tani            );
            list.add(Sapele             );
            list.add(Udu                );
            list.add(Ughelli_North      );
            list.add(Ughelli_South      );
            list.add(Ukwuani            );
            list.add(Uvwie              );
            list.add(Warri_North        );
            list.add(Warri_South        );
            list.add(Warri_South_West   );
            list.add(Abakaliki          );
            list.add(Afikpo_North       );
            list.add(Afikpo_South       );
            list.add(Ebonyi     );
            list.add(Ezza_North);
            list.add(Ezza_South);
            list.add(Ikwo);
            list.add(Ishielu);
            list.add(Ivo);
            list.add(Izzi);
            list.add(Ohaozara);
            list.add(Ohaukwu);
            list.add(Onicha);
            list.add(Akoko_Edo);
            list.add(Egor);
            list.add(Esan_Central);
            list.add(Esan_North_East);
            list.add(Esan_South_East);
            list.add(Esan_West);
            list.add(Etsako_Central);
            list.add(Etsako_East);
            list.add(Etsako_West);
            list.add(Iguegben   );
            list.add(Ikpoba_Okha);
            list.add(Oredo      );
            list.add(Orhionmwon );
            list.add(Ovia_North_East);
            list.add(Ovia_South_West);
            list.add(Owan_East);
            list.add(Owan_West);
            list.add(Uhunmwode);
            list.add(Ado_Ekiti);
            list.add(Efon     );
            list.add(Ekiti_East);
            list.add(Ekiti_South_West);
            list.add(Ekiti_West);
            list.add(Emure);
            list.add(Gbonyin);
            list.add(Ido_Osi);
            list.add(Ijero);
            list.add(Ikere);
            list.add(Ikole);
            list.add(Ilejemeje);
            list.add(Irepodun_Ifelodun);
            list.add(Ise_Orun);
            list.add(Moba);
            list.add(Oye );
            list.add(Aninri);
            list.add(Awgu  );
            list.add(Enugu_East);
            list.add(Enugu_North);
            list.add(Enugu_South);
            list.add(Ezeagu);
            list.add(Igbo_Etiti );
            list.add(Igbo_Eze_North);
            list.add(Igbo_Eze_South);
            list.add(Isi_Uzo);
            list.add(Nkanu_East);
            list.add(Nkanu_West);
            list.add(Nsukka    );
            list.add(Oji_River );
            list.add(Udenu     );
            list.add(Udi       );
            list.add(Uzo_Uwani );
            list.add(Abaji     );
            list.add(Bwari     );
            list.add(Gwagwalada         );
            list.add(Kuje               );
            list.add(Kwali              );
            list.add(Municipal_Area_Council);
            list.add(Akko               );
            list.add(Balanga            );
            list.add(Billiri            );
            list.add(Dukku              );
            list.add(Funakaye           );
            list.add(Gombe              );
            list.add(Kaltungo           );
            list.add(Kwami              );
            list.add(Nafada             );
            list.add(Shomgom            );
            list.add(Yamaltu_Deba       );
            list.add(Aboh_Mbaise        );
            list.add(Ahiazu_Mbaise      );
            list.add(Ehime_Mbano        );
            list.add(Ezinihitte         );
            list.add(Ideato_North       );
            list.add(Ideato_South       );
            list.add(Ihitte_Uboma       );
            list.add(Ikeduru            );
            list.add(Isiala_Mbano       );
            list.add(Isu                );
            list.add(Mbatoli            );
            list.add(Ngor_Okpala        );
            list.add(Njaba              );
            list.add(Nkwerre            );
            list.add(Nwangele           );
            list.add(Obowo              );
            list.add(Oguta              );
            list.add(Ohaji_Egbema       );
            list.add(Okigwe             );
            list.add(Onuimo             );
            list.add(Orlu               );
            list.add(Orsu               );
            list.add(Oru_East           );
            list.add(Oru_West           );
            list.add(Owerri_Municipal   );
            list.add(Owerri_North       );
            list.add(Owerri_West        );
            list.add(Auyo               );
            list.add(Babura             );
            list.add(Biriniwa           );
            list.add(Birnin_Kudu        );
            list.add(Buji               );
            list.add(Dutse              );
            list.add(Gagarawa           );
            list.add(Garki              );
            list.add(Gumel              );
            list.add(Guri               );
            list.add(Gwaram             );
            list.add(Gwiwa              );
            list.add(Hadejia            );
            list.add(Jahun              );
            list.add(Kafin_Hausa        );
            list.add(Kaugama            );
            list.add(Kazaure            );
            list.add(Kiri_Kasama        );
            list.add(Kiyawa             );
            list.add(Maigatari          );
            list.add(Malam_Madori       );
            list.add(Miga               );
            list.add(Ringim             );
            list.add(Roni               );
            list.add(Sule_Tankarkar     );
            list.add(Taura              );
            list.add(Yankwashi          );
            list.add(Aleiro             );
            list.add(Arewa_Dandi        );
            list.add(Argungu            );
            list.add(Augie              );
            list.add(Bagudo             );
            list.add(Birnin_Kebbi       );
            list.add(Bunza              );
            list.add(Dandi              );
            list.add(Fakai              );
            list.add(Gwandu             );
            list.add(Jega               );
            list.add(Kalgo              );
            list.add(Koko_Besse         );
            list.add(Maiyama            );
            list.add(Ngaski             );
            list.add(Sakaba             );
            list.add(Shanga             );
            list.add(Suru_Zuru          );
            list.add(Wasagu_Danko       );
            list.add(Yauri              );
            list.add(Zuru               );
            list.add(Birnin_Gwari       );
            list.add(Chikun             );
            list.add(Giwa               );
            list.add(Igabi              );
            list.add(Ikara              );
            list.add(J_aba              );
            list.add(Jema_a             );
            list.add(Kachia             );
            list.add(Kaduna_North       );
            list.add(Kaduna_South       );
            list.add(Kagarko            );
            list.add(Kajuru             );
            list.add(Kaura              );
            list.add(kauru              );
            list.add(Kubau              );
            list.add(Kudan              );
            list.add(Lere               );
            list.add(Makarfi            );
            list.add(Sabon_Gari         );
            list.add(Sanga              );
            list.add(Soba               );
            list.add(Zangon_Kataf       );
            list.add(Zaria              );
            list.add(Adavi              );
            list.add(Ajaokuta           );
            list.add(Ankpa              );
            list.add(Bassa              );
            list.add(Dekina             );
            list.add(Ibaji              );
            list.add(Idah               );
            list.add(Igalamela_Odolu    );
            list.add(Ijumu              );
            list.add(Kabba_Bunu         );
            list.add(Kogi               );
            list.add(Lokoja             );
            list.add(Mopa_Muro          );
            list.add(Ofu                );
            list.add(Ogori_Magongo      );
            list.add(Okehi              );
            list.add(Okene              );
            list.add(Olamaboro          );
            list.add(Omala              );
            list.add(Yagba_East         );
            list.add(Yagba_West         );
            list.add(Ajingi             );
            list.add(Albasu             );
            list.add(Bagwai             );
            list.add(Bebeji             );
            list.add(Bichi              );
            list.add(Bunkure            );
            list.add(Dala               );
            list.add(Dambatta           );
            list.add(Dawakin_Kudu       );
            list.add(Dawakin_Tofa       );
            list.add(Doguwa             );
            list.add(Fagge              );
            list.add(Gabasawa           );
            list.add(Garko              );
            list.add(Garum_Mallam       );
            list.add(Gaya               );
            list.add(Gezawa             );
            list.add(Gwale              );
            list.add(Gwarzo             );
            list.add(Kabo               );
            list.add(Kano_Municipal     );
            list.add(Karaye             );
            list.add(Kibiya             );
            list.add(Kiru               );
            list.add(Kumbotso           );
            list.add(Kunchi             );
            list.add(Kura               );
            list.add(Madobi             );
            list.add(Makoda             );
            list.add(Minjibir           );
            list.add(Nassarawa_Kano     );
            list.add(Rano               );
            list.add(Rimin_Gado         );
            list.add(Rogo               );
            list.add(Shanono            );
            list.add(Sumaila            );
            list.add(Takai              );
            list.add(Tarauni            );
            list.add(Tofa               );
            list.add(Tsanyawa           );
            list.add(Tudun_Wada         );
            list.add(Ungongo            );
            list.add(Warawa             );
            list.add(Wudil              );
            list.add(Bakori             );
            list.add(Batagarawa         );
            list.add(Batsari            );
            list.add(Baure              );
            list.add(Bindawa            );
            list.add(Charanchi          );
            list.add(Dan_Musa           );
            list.add(Dandume            );
            list.add(Danja              );
            list.add(Daura              );
            list.add(Dutsi              );
            list.add(Dutsin_Ma          );
            list.add(Faskari            );
            list.add(Funtua             );
            list.add(Ingawa             );
            list.add(Jibia              );
            list.add(Kafur              );
            list.add(Kaita              );
            list.add(Kankara            );
            list.add(Kankia             );
            list.add(Katsina            );
            list.add(Kurfi              );
            list.add(Kusada             );
            list.add(Mai_adua           );
            list.add(Malumfashi         );
            list.add(Mani               );
            list.add(Mashi              );
            list.add(Matazu             );
            list.add(Musawa             );
            list.add(Rimi               );
            list.add(Sabuwa             );
            list.add(Safana             );
            list.add(Sandamu            );
            list.add(Zango              );
            list.add(Asa                );
            list.add(Baruten            );
            list.add(Edu                );
            list.add(Ekiti              );
            list.add(Ifelodun_Kwara);
            list.add(Ilorin_East        );
            list.add(Ilorin_South       );
            list.add(Ilorin_West        );
            list.add(Irepodun_Kwara     );
            list.add(Isin               );
            list.add(Kaiama             );
            list.add(Moro               );
            list.add(Offa               );
            list.add(Oke_Ero            );
            list.add(Oyun               );
            list.add(Pategi             );
            list.add(Epe                );
            list.add(Ibeju_Lekki        );
            list.add(Eti_Osa            );
            list.add(Lagos_Island       );
            list.add(Amuwo_Odofin       );
            list.add(Apapa              );
            list.add(Ajeromi_Ifelodun   );
            list.add(Badagry            );
            list.add(Ojo                );
            list.add(Oshodi_Isolo       );
            list.add(Alimosho           );
            list.add(Agege              );
            list.add(Ifako_Ijaye        );
            list.add(Mushin             );
            list.add(Ikeja              );
            list.add(Surulere           );
            list.add(Shomolu            );
            list.add(Lagos_Mainland     );
            list.add(Ikorodu            );
            list.add(Kosofe             );
            list.add(Akwanga            );
            list.add(Nassarawa_Egon     );
            list.add(Wamba              );
            list.add(Karu               );
            list.add(Keffi              );
            list.add(Kokona             );
            list.add(Doma               );
            list.add(Lafia              );
            list.add(Nassarawa          );
            list.add(Toto               );
            list.add(Keana              );
            list.add(Awe                );
            list.add(O_bi               );
            list.add(Agaie              );
            list.add(Agwara             );
            list.add(Bida               );
            list.add(Borgu              );
            list.add(Bosso              );
            list.add(Chanchaga          );
            list.add(Edati              );
            list.add(Gbako              );
            list.add(Gurara             );
            list.add(Katcha             );
            list.add(Kontagora          );
            list.add(Lapai              );
            list.add(Lavun              );
            list.add(Magama             );
            list.add(Mairiga            );
            list.add(Mashegu            );
            list.add(Mokwa              );
            list.add(Muya               );
            list.add(Paikoro            );
            list.add(Rafi               );
            list.add(Rijau              );
            list.add(Shiroro            );
            list.add(Suleja             );
            list.add(Tafa               );
            list.add(Wushishi           );
            list.add(Ifedore            );
            list.add(Ile_Oluji_Okeigbo  );
            list.add(Akure_North        );
            list.add(Akure_South        );
            list.add(Ose                );
            list.add(Owo                );
            list.add(Akoko_North_West   );
            list.add(Akoko_North_East   );
            list.add(Akoko_South_East   );
            list.add(Akoko_South_West   );
            list.add(Idanre             );
            list.add(Ondo_East          );
            list.add(Ondo_West          );
            list.add(Odigbo             );
            list.add(Ese_Odo            );
            list.add(Ilaje              );
            list.add(Okitipupa          );
            list.add(Irele              );
            list.add(Imeko_Afon         );
            list.add(Abeokuta_South     );
            list.add(Abeokuta_North     );
            list.add(Egbado_North       );
            list.add(Egbado_South       );
            list.add(Ikenne             );
            list.add(Shagamu            );
            list.add(Ipokia             );
            list.add(Ado_Odo_Otta       );
            list.add(Ewekoro            );
            list.add(Ifo                );
            list.add(Odeda              );
            list.add(Obafemi_Owode      );
            list.add(Ogun_waterside     );
            list.add(Ijebu_East         );
            list.add(Ijebu_ode          );
            list.add(Remo_North         );
            list.add(Ijebu_North        );
            list.add(Ijebu_North_East   );
            list.add(Odogbolu);
            list.add(Aiyedaade           );
            list.add(Aiyedire            );
            list.add(Atakunmosa_East     );
            list.add(Atakunmosa_West     );
            list.add(Boluwaduro          );
            list.add(Boripe              );
            list.add(Ede_North           );
            list.add(Ede_South           );
            list.add(Egbedore            );
            list.add(Ejigbo              );
            list.add(Ife_Cen_tral        );
            list.add(Ife_East            );
            list.add(Ife_North           );
            list.add(Ife_South           );
            list.add(Ifedayo             );
            list.add(Ife_lodun           );
            list.add(Ila                 );
            list.add(Ilesha_East         );
            list.add(Ilesha_West         );
            list.add(Irepodun            );
            list.add(Irewole             );
            list.add(Isokan              );
            list.add(Iwo                 );
            list.add(Obokun              );
            list.add(Odo_Otin            );
            list.add(Ola_oluwa           );
            list.add(Olorunda            );
            list.add(Oriade              );
            list.add(Orolu               );
            list.add(Osogbo              );
            list.add(Ibadan_North_East   );
            list.add(Ibadan_South_West   );
            list.add(Ibadan_South_East   );
            list.add(Ido                 );
            list.add(Afijio              );
            list.add(Akinyele            );
            list.add(Egbeda              );
            list.add(Oluyole             );
            list.add(Ona_ara             );
            list.add(Lagelu              );
            list.add(Ogo_Oluwa           );
            list.add(Suru_lere           );
            list.add(Ogbomosho_North     );
            list.add(Ogbomosho_South     );
            list.add(Atisbo              );
            list.add(Irepo               );
            list.add(Orelope             );
            list.add(Saki_West           );
            list.add(Saki_East           );
            list.add(Atiba               );
            list.add(Iwajowa             );
            list.add(Kajola              );
            list.add(Itesiwaju           );
            list.add(Ori_Ire             );
            list.add(Olorunsogo          );
            list.add(Ibarapa_Central     );
            list.add(Ibarapa_East        );
            list.add(Ibarapa_North       );
            list.add(Iseyin              );
            list.add(Oyo_East            );
            list.add(Oyo_West            );
            list.add(Ibadan_North_West   );
            list.add(Ibadan_North        );
            list.add(Mangu               );
            list.add(Quaan_Pan           );
            list.add(Bokkos              );
            list.add(Riyom               );
            list.add(Barkin_Ladi         );
            list.add(Pank_shin           );
            list.add(Kanam               );
            list.add(Kanke               );
            list.add(Jos_North           );
            list.add(Jos_South           );
            list.add(Jos_East            );
            list.add(Bas_sa              );
            list.add(Mikang              );
            list.add(Shendam             );
            list.add(Langtang_North      );
            list.add(Langtang_South      );
            list.add(Wase                );
            list.add(Abua_Odual          );
            list.add(Ahoada_East         );
            list.add(Ahoada_West         );
            list.add(Akuku_Toru          );
            list.add(Andoni              );
            list.add(Asari_Toru          );
            list.add(Bonny               );
            list.add(Degema              );
            list.add(Eleme               );
            list.add(Emuoha              );
            list.add(Etche               );
            list.add(Gokana              );
            list.add(Ikwerre             );
            list.add(Khana               );
            list.add(Obio_Akpor          );
            list.add(Ogba_Egbema_Ndoni   );
            list.add(Ogu_Bolo            );
            list.add(Okrika              );
            list.add(Omumma              );
            list.add(Opobo_Nkoro         );
            list.add(Oyigbo              );
            list.add(Port_Harcourt       );
            list.add(Tai                 );
            list.add(Binji               );
            list.add(Bodinga             );
            list.add(Dange_Shuni         );
            list.add(Gada                );
            list.add(Goronyo             );
            list.add(Gudu                );
            list.add(Gwadabawa           );
            list.add(Illela              );
            list.add(Isa                 );
            list.add(Kebbe               );
            list.add(Kware               );
            list.add(Rabah               );
            list.add(Sabon_Birni         );
            list.add(Shagari             );
            list.add(Silame              );
            list.add(Sokoto_North        );
            list.add(Sokoto_South        );
            list.add(Tambuwal            );
            list.add(Tangaza             );
            list.add(Tureta              );
            list.add(Wamako              );
            list.add(Wurno               );
            list.add(Yabo                );
            list.add(Ardo_Kola           );
            list.add(Bali                );
            list.add(Donga               );
            list.add(Gashaka             );
            list.add(Gassol              );
            list.add(Ibi                 );
            list.add(Jalingo             );
            list.add(Karim_Lamido        );
            list.add(Kurmi               );
            list.add(Lau                 );
            list.add(Sardauna            );
            list.add(Takum               );
            list.add(Ussa                );
            list.add(Wukari              );
            list.add(Yorro               );
            list.add(Zing                );
            list.add(Barde               );
            list.add(Bursari             );
            list.add(Damaturu            );
            list.add(Fika                );
            list.add(Fune                );
            list.add(Geidam              );
            list.add(Gujba               );
            list.add(Gulani              );
            list.add(Jakusko             );
            list.add(Karasuwa            );
            list.add(Machina             );
            list.add(Nangere             );
            list.add(Nguru               );
            list.add(Potiskum            );
            list.add(Tarmuwa             );
            list.add(Yunusari            );
            list.add(Yusufari            );
            list.add(Anka                );
            list.add(Bakura              );
            list.add(Birnin_Magaji_Kiyaw );
            list.add(Bukkuyum            );
            list.add(Bungudu             );
            list.add(Gummi               );
            list.add(Gusau               );
            list.add(Kaura_Namoda        );
            list.add(Maradun             );
            list.add(Maru                );
            list.add(Shinkafi            );
            list.add(Talata_Mafara       );
            list.add(Tsafe               );
            list.add(Zurmi               );




            return list;
        }

        public class Lga {
            private String code;
            private String description;


            public Lga(String code, String description) {
                this.code = code;
                this.description = description;
            }


            public String getCode() {
                return code;
            }

            public void setCode(String code) {
                this.code = code;
            }

            public String getDescription() {
                return description;
            }

            public void setDescription(String description) {
                this.description = description;
            }
        }

}
